services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/doubtdesk_db
      - SPRING_DATASOURCE_USERNAME=doubtdesk_user
      - SPRING_DATASOURCE_PASSWORD=your_secure_password
      - file.upload-dir=/app/uploads # এই লাইনটি যোগ করুন
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads # এই লাইনটি যোগ করুন

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mi31122004@#
      MYSQL_DATABASE: doubtdesk_db
      MYSQL_USER: doubtdesk_user
      MYSQL_PASSWORD: your_secure_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data: